language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
    - "pypy3"
addons:
  apt:
    update: true
    packages:
    - enchant
install:
    - pip install -rrequirements.txt
    - pip install -rtest-requirements.txt
    - pip install -e ./
script:
    - if [[ "$(python --version 2>&1)" =~ Python\ (2\.7.*|3\.[3-4].*) ]]; then pep8 venvctrl/; else echo "Skipping PEP8 for $(python --version 2>&1)."; fi
    - if [[ "$(python --version 2>&1)" =~ Python\ (2\.7.*|3\.[3-4].*) ]]; then pyflakes venvctrl/; else echo "Skipping PyFlakes for $(python --version 2>&1)."; fi
    - if [[ "$(python --version 2>&1)" =~ Python\ (2\.7.*|3\.[3-4].*) ]]; then pylint --rcfile=.pylintrc venvctrl/; else echo "Skipping PyLint for $(python --version 2>&1)."; fi
    - py.test tests/
